INSERT INTO Drone (ID , SERIALNO, MODEL, WEIGHT_LIMIT, BATTERY_CAPACITY, STATE) values (1, '1234567', 'LIGHTWEIGHT' , '200' ,  '15' , 'IDLE' )
INSERT INTO Drone (ID , SERIALNO, MODEL, WEIGHT_LIMIT, BATTERY_CAPACITY, STATE) values (2, '1235567', 'MIDDLEWEIGHT' , '300' ,  '90' , 'IDLE' )
INSERT INTO Drone (ID , SERIALNO, MODEL, WEIGHT_LIMIT, BATTERY_CAPACITY, STATE) values (3, '1236467', 'LIGHTWEIGHT' , '150' ,  '80' , 'LOADING' )
INSERT INTO Drone (ID , SERIALNO, MODEL, WEIGHT_LIMIT, BATTERY_CAPACITY, STATE) values (4, '1234867', 'LIGHTWEIGHT' , '250' ,  '30' , 'LOADED' )
INSERT INTO Drone (ID , SERIALNO, MODEL, WEIGHT_LIMIT, BATTERY_CAPACITY, STATE) values (5, '1239867', 'MIDDLEWEIGHT' , '300' ,  '100' , 'DELIVERING' )
INSERT INTO Drone (ID , SERIALNO, MODEL, WEIGHT_LIMIT, BATTERY_CAPACITY, STATE) values (6, '1237867', 'CRUISERWEIGHT' , '350' ,  '60' , 'DELIVERED' )
INSERT INTO Drone (ID , SERIALNO, MODEL, WEIGHT_LIMIT, BATTERY_CAPACITY, STATE) values (7, '9834567', 'CRUISERWEIGHT' , '360' ,  '90' , 'RETURNING' )
INSERT INTO Drone (ID , SERIALNO, MODEL, WEIGHT_LIMIT, BATTERY_CAPACITY, STATE) values (8, '1534567', 'HEAVYWEIGHT' , '450' ,  '95' , 'LOADED' )
INSERT INTO Drone (ID , SERIALNO, MODEL, WEIGHT_LIMIT, BATTERY_CAPACITY, STATE) values (9, '8234567', 'HEAVYWEIGHT' , '500' ,  '15' , 'LOADING' )



INSERT INTO Medication (ID , NAME, CODE,WEIGHT ,DRONE_ID) values (1, 'Acetaminophen', '38BEE27' , '100' , 5)
INSERT INTO Medication (ID , NAME, CODE,WEIGHT ,DRONE_ID) values (2, 'Adderall', '48BFE27' , '200' ,5)
INSERT INTO Medication (ID , NAME, CODE,WEIGHT ,DRONE_ID) values (3, 'Amitriptyline', '59BTE27' , '50', 6)
INSERT INTO Medication (ID , NAME, CODE,WEIGHT ,DRONE_ID) values (4, 'Amlodipine', '18BER27' , '300',6)
INSERT INTO Medication (ID , NAME, CODE,WEIGHT ,DRONE_ID) values (5, 'Amoxicillin', '28BEQ27' , '500',9)






